// Maps seed-pack district IDs (UG-D0xx) to our district IDs (src/data/districts.ts).
// Generated by matching district_name (case-insensitive). 34/50 matched; the
// 16 unmatched seed districts (Luwero, Mityana, Mubende, Kayunga, Buvuma, Kamuli,
// Napak, Koboko, Nebbi, Kiryandongo, Fort Portal, Kabarole, Ntoroko, Kanungu,
// Isingiro, Sembabule) are not in our 46-district set and map to null.

export const SEED_TO_OUR_ID: Record<string, string | null> = {
  'UG-D001': 'kampala',
  'UG-D002': 'wakiso',
  'UG-D003': 'mukono',
  'UG-D004': 'masaka',
  'UG-D005': null,
  'UG-D006': null,
  'UG-D007': null,
  'UG-D008': 'mpigi',
  'UG-D009': null,
  'UG-D010': 'kalangala',
  'UG-D011': null,
  'UG-D012': 'jinja',
  'UG-D013': 'iganga',
  'UG-D014': 'mayuge',
  'UG-D015': null,
  'UG-D016': 'mbale',
  'UG-D017': 'tororo',
  'UG-D018': 'busia',
  'UG-D019': 'soroti',
  'UG-D020': 'kumi',
  'UG-D021': 'kapchorwa',
  'UG-D022': 'moroto',
  'UG-D023': 'kotido',
  'UG-D024': 'kaabong',
  'UG-D025': null,
  'UG-D026': 'gulu',
  'UG-D027': 'lira',
  'UG-D028': 'arua',
  'UG-D029': 'yumbe',
  'UG-D030': null,
  'UG-D031': 'adjumani',
  'UG-D032': 'moyo',
  'UG-D033': null,
  'UG-D034': 'masindi',
  'UG-D035': 'hoima',
  'UG-D036': null,
  'UG-D037': null,
  'UG-D038': null,
  'UG-D039': 'kasese',
  'UG-D040': 'bundibugyo',
  'UG-D041': null,
  'UG-D042': 'mbarara',
  'UG-D043': 'bushenyi',
  'UG-D044': 'ntungamo',
  'UG-D045': 'rukungiri',
  'UG-D046': 'kabale',
  'UG-D047': 'kisoro',
  'UG-D048': null,
  'UG-D049': null,
  'UG-D050': null,
}

// our district id -> seed district id (only for matched districts)
export const OUR_TO_SEED_ID: Record<string, string> = Object.fromEntries(
  Object.entries(SEED_TO_OUR_ID)
    .filter((entry): entry is [string, string] => entry[1] !== null)
    .map(([seedId, ourId]) => [ourId, seedId])
)
